# Generated by Django 4.2.5 on 2023-09-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sellerreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('pic', models.FileField(upload_to='ecommerceapp/static')),
                ('cname', models.CharField(max_length=30)),
                ('cdetail', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
