# Generated by Django 4.2.5 on 2023-09-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='seller_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='ecommerceapp/static')),
                ('price', models.IntegerField()),
                ('colors', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids')], max_length=30)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
