# Generated by Django 4.2.5 on 2023-09-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_seller_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_file',
            name='quantity',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seller_file',
            name='colors',
            field=models.CharField(choices=[('Silver', 'Silver'), ('Gold', 'Gold'), ('RoseGold', 'RoseGold'), ('Black', 'Black')], max_length=15),
        ),
    ]
