# Generated by Django 4.2.5 on 2023-09-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_seller_file_quantity_alter_seller_file_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyerreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('loc', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
