# Generated by Django 4.2.5 on 2023-09-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_buyerreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerreg',
            name='pic',
            field=models.FileField(default=2, upload_to='ecommerceapp/static'),
            preserve_default=False,
        ),
    ]
