# Generated by Django 4.2.5 on 2023-09-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0006_buyer_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer_wishlist',
            name='brand',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyer_wishlist',
            name='prod_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
