# Generated by Django 4.2.5 on 2023-09-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0007_buyer_wishlist_brand_buyer_wishlist_prod_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('prod_id', models.IntegerField()),
                ('brand', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
    ]
