# Generated by Django 4.2.5 on 2023-09-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0008_add_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_cart',
            name='desc',
        ),
        migrations.AddField(
            model_name='add_cart',
            name='pic',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
