# Generated by Django 4.2.5 on 2023-09-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0009_remove_add_cart_desc_add_cart_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='address_change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('daddress', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('Kerala', 'Kerala'), ('Tamilnadu', 'Tamilnadu'), ('Karnataka', 'Karnataka')], max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('houseno', models.CharField(max_length=20)),
                ('landmark', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
                ('phn', models.IntegerField()),
                ('alt_phn', models.IntegerField()),
            ],
        ),
    ]
