# Generated by Django 4.2.5 on 2023-10-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0010_address_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_confirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('imgg', models.FileField(upload_to='')),
                ('prod_details', models.CharField(max_length=500)),
                ('total', models.IntegerField()),
                ('order_date', models.DateField(auto_now_add=True)),
                ('esimated_date', models.DateField()),
            ],
        ),
    ]
